#!/bin/bash

ROOT_UID=0

if [ "$UID" -eq "$ROOT_UID" ]; then

  # Copy StylishDark
  cp -a StylishDark /boot/grub/themes

  # Set StylishDark
  grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME=/d' /etc/default/grub
  echo "GRUB_THEME=\"/boot/grub/themes/StylishDark/theme.txt\"" >> /etc/default/grub

  # update grub
  grub-mkconfig -o /boot/grub/grub.cfg

  echo -e "\n All done!"

else
  echo -e "\n Please run this script by root..."
fi


