#!/bin/bash

# Slaze - Grub2 Abstract Theme

ROOT_UID=0

# Welcome message
echo -e "\n\t**********************************\n\t*  Slaze - Grub2 Abstract Theme  *\n\t**********************************"

# Check command avalibility
function has_command() {
  command -v $1 > /dev/null
}

echo -e "\nChecking for root access..."

# Checking for root access and proceed if it is present
if [ "$UID" -eq "$ROOT_UID" ]; then

  # Create themes directory if not exists
  echo -e "Checking for the existence of themes directory..."
  mkdir -p /boot/grub/themes

  # Copy Slaze
  echo -e "Installing Slaze theme..."
  cp -a Slaze /boot/grub/themes

  # Set Slaze
  echo -e "Setting Slaze as default..."
  grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME=/d' /etc/default/grub
  echo "GRUB_THEME=\"/boot/grub/themes/Slaze/theme.txt\"" >> /etc/default/grub

  # Update grub config
  echo -e "Updating grub config..."
  if has_command update-grub; then
    update-grub
  elif has_command grub-mkconfig; then
    grub-mkconfig -o /boot/grub/grub.cfg
  fi

  # Success message
  echo -e "\n\t          ***************\n\t          *  All done!  *\n\t          ***************\n"

else
  # Error message
  echo -e "\n\t  ******************************\n\t  *  Error! -> Run me as root  *\n\t  ******************************\n"
fi
