#!/bin/bash

# Vimix - Grub2 Flat Theme

ROOT_UID=0

# Welcome message
echo -e "\n\t******************************\n\t*  Vimix - Grub2 Flat Theme  *\n\t******************************"

# Check command avalibility
function has_command() {
  command -v $1 > /dev/null
}

echo -e "\nChecking for root access..."

# Checking for root access and proceed if it is present
if [ "$UID" -eq "$ROOT_UID" ]; then

  # Create themes directory if not exists
  echo -e "Checking for the existence of themes directory..."
  mkdir -p /boot/grub/themes

  # Copy Vimix
  echo -e "Installing Vimix theme..."
  cp -a Vimix /boot/grub/themes

  # Set Vimix
  echo -e "Setting Vimix as default..."
  grep "GRUB_THEME=" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME=/d' /etc/default/grub
  echo "GRUB_THEME=\"/boot/grub/themes/Vimix/theme.txt\"" >> /etc/default/grub

  # Update grub config
  echo -e "Updating grub config..."
  if has_command update-grub; then
    update-grub
  elif has_command grub-mkconfig; then
    grub-mkconfig -o /boot/grub/grub.cfg
  fi

  # Success message
  echo -e "\n\t       ***************\n\t       *  All done!  *\n\t       ***************\n"

else
  # Error message
  echo -e "\n\t******************************\n\t*  Error! -> Run me as root  *\n\t******************************\n"
fi
